artifact_location: file:D:/datasethub/backend/Dataset_Management_tool/runs/mlflow/328895089280378580
creation_time: 1772863203376
experiment_id: '328895089280378580'
last_update_time: 1772863203376
lifecycle_stage: active
name: D:\datasethub\datasethub_storage\training\jobs\07d6caf6-5eb3-4595-9971-9b4db0e75f50\runs
workspace: default
