artifact_location: file:D:/datasethub/backend/Dataset_Management_tool/runs/mlflow/570847955795633609
creation_time: 1772447708165
experiment_id: '570847955795633609'
last_update_time: 1772447708165
lifecycle_stage: active
name: D:\datasethub\datasethub_storage\training\jobs\c7dcdea4-0d5e-4e95-b329-ec8223035c66\runs
workspace: default
